#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# docker-stacks documentation build configuration file, created by
# sphinx-quickstart on Fri Dec 29 20:32:10 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
<<<<<<< HEAD
needs_sphinx = '1.4'
=======
needs_sphinx = "2.1"
>>>>>>> 70178b8e48d7825ceade6e2decf374bc3e792d90

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
<<<<<<< HEAD
extensions = [
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'docker-stacks'
copyright = '2018- Project Jupyter'
author = 'Project Jupyter'
=======
extensions = ["myst_parser", "sphinx_copybutton"]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

source_suffix = {
    ".rst": "restructuredtext",
    ".md": "markdown",
}

# The master toctree document.
master_doc = "index"

# General information about the project.
project = "docker-stacks"
copyright = "2018- Project Jupyter"
author = "Project Jupyter"
>>>>>>> 70178b8e48d7825ceade6e2decf374bc3e792d90

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
<<<<<<< HEAD
version = 'latest'
# The full version, including alpha/beta/rc tags.
release = 'latest'
=======
version = "latest"
# The full version, including alpha/beta/rc tags.
release = "latest"
>>>>>>> 70178b8e48d7825ceade6e2decf374bc3e792d90

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
<<<<<<< HEAD
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'
=======
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"
>>>>>>> 70178b8e48d7825ceade6e2decf374bc3e792d90

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


<<<<<<< HEAD
# -- Source -------------------------------------------------------------

source_parsers = {
    '.md': 'recommonmark.parser.CommonMarkParser',
}

source_suffix = ['.rst', '.md']

=======
>>>>>>> 70178b8e48d7825ceade6e2decf374bc3e792d90
# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
<<<<<<< HEAD
html_theme = 'alabaster'
=======
html_theme = "alabaster"
>>>>>>> 70178b8e48d7825ceade6e2decf374bc3e792d90

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
html_theme_options = {
<<<<<<< HEAD
    'description': "Jupyter Docker Stacks",
    'fixed_sidebar': False,
    'show_relbars': True,
    'github_user': 'jupyter',
    'github_repo': 'docker-stacks',
    'github_type': 'star',
    'logo': 'jupyter-logo.png',
    'logo_text_align': 'left'
=======
    "description": "Jupyter Docker Stacks",
    "fixed_sidebar": False,
    "show_relbars": True,
    "github_user": "jupyter",
    "github_repo": "docker-stacks",
    "github_type": "star",
    "logo": "jupyter-logo.svg",
    "logo_text_align": "left",
>>>>>>> 70178b8e48d7825ceade6e2decf374bc3e792d90
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
<<<<<<< HEAD
html_static_path = ['_static']
=======
html_static_path = ["_static"]
>>>>>>> 70178b8e48d7825ceade6e2decf374bc3e792d90

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
html_sidebars = {
<<<<<<< HEAD
    '**': [
        'about.html',
        'navigation.html',
        'relations.html',
        'searchbox.html',
=======
    "**": [
        "about.html",
        "navigation.html",
        "relations.html",
        "searchbox.html",
>>>>>>> 70178b8e48d7825ceade6e2decf374bc3e792d90
    ]
}

# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
<<<<<<< HEAD
htmlhelp_basename = 'docker-stacksdoc'
=======
htmlhelp_basename = "docker-stacksdoc"
>>>>>>> 70178b8e48d7825ceade6e2decf374bc3e792d90


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',
<<<<<<< HEAD

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

=======
    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',
>>>>>>> 70178b8e48d7825ceade6e2decf374bc3e792d90
    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
<<<<<<< HEAD
    (master_doc, 'docker-stacks.tex', 'docker-stacks Documentation',
     'Project Jupyter', 'manual'),
=======
    (
        master_doc,
        "docker-stacks.tex",
        "docker-stacks Documentation",
        "Project Jupyter",
        "manual",
    ),
>>>>>>> 70178b8e48d7825ceade6e2decf374bc3e792d90
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
<<<<<<< HEAD
man_pages = [
    (master_doc, 'docker-stacks', 'docker-stacks Documentation',
     [author], 1)
]
=======
man_pages = [(master_doc, "docker-stacks", "docker-stacks Documentation", [author], 1)]
>>>>>>> 70178b8e48d7825ceade6e2decf374bc3e792d90


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
<<<<<<< HEAD
    (master_doc, 'docker-stacks', 'docker-stacks Documentation',
     author, 'docker-stacks', 'One line description of project.',
     'Miscellaneous'),
=======
    (
        master_doc,
        "docker-stacks",
        "docker-stacks Documentation",
        author,
        "docker-stacks",
        "One line description of project.",
        "Miscellaneous",
    ),
>>>>>>> 70178b8e48d7825ceade6e2decf374bc3e792d90
]

# -- Extension configuration ----------------------------------------------

# Anchors are often dynamic
linkcheck_anchors = False

# -- Translation ----------------------------------------------------------

gettext_uuid = True
<<<<<<< HEAD
locale_dirs = ['locale/']
=======
locale_dirs = ["locale/"]
>>>>>>> 70178b8e48d7825ceade6e2decf374bc3e792d90
