<<<<<<< HEAD
name: Build Docker Images

on:
  pull_request:
    paths-ignore:
=======
name: Build, test, and publish Docker Images

on:
  schedule:
    # Weekly, at 03:00 on Monday UTC time
    - cron: "0 3 * * 1"
  pull_request:
    paths-ignore:
      - ".github/ISSUE_TEMPLATE/**"
>>>>>>> 70178b8e48d7825ceade6e2decf374bc3e792d90
      - "*.md"
      - "binder/**"
      - "docs/**"
      - "examples/**"
<<<<<<< HEAD
  push:
    branches:
      - master
    paths-ignore:
=======
      - ".pre-commit-config.yaml"
  push:
    branches:
      - master
      - main
    paths-ignore:
      - ".github/ISSUE_TEMPLATE/**"
>>>>>>> 70178b8e48d7825ceade6e2decf374bc3e792d90
      - "*.md"
      - "binder/**"
      - "docs/**"
      - "examples/**"
<<<<<<< HEAD

jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    if: >
      !contains(github.event.head_commit.message, 'ci skip') &&
      !contains(github.event.pull_request.title, 'ci skip')
    steps:
=======
      - ".pre-commit-config.yaml"

jobs:
  build-test-publish-images:
    name: Build, test, and publish Docker Images
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: >
      !contains(github.event.head_commit.message, 'ci skip') &&
      !contains(github.event.pull_request.title, 'ci skip')

    steps:
      # Setup docker to build for multiple platforms, see:
      # https://github.com/docker/build-push-action/tree/master#usage
      # https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md
      - name: Set up QEMU (for docker buildx)
        uses: docker/setup-qemu-action@27d0a4f181a40b142cce983c5393082c365d1480 # dependabot updates to latest release

      - name: Set up Docker Buildx (for multi-arch builds)
        uses: docker/setup-buildx-action@abe5d8f79a1606a2d3e218847032f3f2b1726ab0 # dependabot updates to latest release
        with:
          version: latest

>>>>>>> 70178b8e48d7825ceade6e2decf374bc3e792d90
      - name: Clone Main Repo
        uses: actions/checkout@v2
        with:
          path: main
<<<<<<< HEAD
      - name: Clone Wiki
        uses: actions/checkout@v2
        with:
          repository: ${{github.repository}}.wiki
          path: wiki
      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Dev Dependencies
        run: |
          python -m pip install --upgrade pip
          make -C main dev-env hadolint-install
      - name: Lint Dockerfiles
        run: make -C main hadolint-all
      - name: Run pre-commit hooks
        run: make -C main pre-commit-all
      - name: Build Docker Images
        run: make -C main build-test-all
        env:
          # Full logs for CI build
          BUILDKIT_PROGRESS: plain
      - name: Run Post-Build Hooks
        run: make -C main hook-all
        env:
          COMMIT_MSG: "${{github.event.head_commit.message}}"
          WIKI_PATH: ../wiki
      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/master'
        run: >
          echo '${{secrets.DOCKERHUB_PASSWORD}}' | docker login --username
          '${{secrets.DOCKERHUB_USERNAME}}' --password-stdin
      - name: Push Images to DockerHub
        if: github.ref == 'refs/heads/master'
        run: make -C main push-all
      - name: Push Wiki to GitHub
        if: github.ref == 'refs/heads/master'
        # Pass GITHUB_REPOSITORY directly to avoid conflict with GitHub Actions built-in env var
        run: make -C main git-commit GITHUB_REPOSITORY='${{ github.repository }}.wiki'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LOCAL_PATH: ../wiki
=======

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dev Dependencies
        run: |
          python -m pip install --upgrade pip
          make -C main dev-env

      - name: Build Docker Images
        run: make -C main build-all-multi
        env:
          # Full logs for CI build
          BUILDKIT_PROGRESS: plain

      - name: Test Docker Images
        run: make -C main test-all

      - name: Clone Wiki
        uses: actions/checkout@v2
        with:
          repository: ${{github.repository}}.wiki
          path: wiki

      - name: Run Post-Build Hooks
        id: hook-all
        run: make -C main hook-all

      - name: Push Wiki to GitHub
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' || github.event_name == 'schedule'
        uses: stefanzweifel/git-auto-commit-action@5dd17c3b53a58c1cb5eaab903826abe94765ccd6 # dependabot updates to latest release
        with:
          commit_message: "[ci skip] Automated publish for ${{github.sha}}"
          repository: wiki/

      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' || github.event_name == 'schedule'
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9 # dependabot updates to latest release
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Push Images to DockerHub
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' || github.event_name == 'schedule'
        run: make -C main push-all-multi
>>>>>>> 70178b8e48d7825ceade6e2decf374bc3e792d90
